info:
  title: movies collection
  version: 1.0.0
openapi: 3.0.0
paths:
  /movies:
    get:
      responses:
        '200':
          description: A list of movies
      summary: Retrieve all movies
    post:
      requestBody:
        content:
          application/json:
            example:
              title: cast away
            schema:
              properties:
                title:
                  type: string
              type: object
      responses:
        '201':
          description: Movie added successfully
      summary: Add a new movie
  /movies/{id}:
    delete:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Movie deleted
      summary: Delete a movie by ID
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            example:
              completed: true
            schema:
              properties:
                completed:
                  type: boolean
              type: object
      responses:
        '200':
          description: Movie info updated
      summary: Update movie info
  /movies/{name}:
    get:
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Movie info retrieved
      summary: Get movie info by name